language: perl
perl:
  - "5.6.2"
  - "5.8.1"
  - "5.8.1-thr"
  - "5.8.5"
  - "5.8.5-thr"
  - "5.8.7"
  - "5.8.7-thr"
  - "5.8.8"
  - "5.8.8-thr"
  - "5.8.9"
  - "5.8.9-thr"
  - "5.10.0"
  - "5.10.0-thr"
  - "5.10.1"
  - "5.10.1-thr"
  - "5.12.5"
  - "5.12.5-thr"
  - "5.14.4"
  - "5.14.4-thr"
  - "5.16.3"
  - "5.16.3-thr"
  - "5.18.1"
  - "5.18.1-thr"
  - "5.18.2"
  - "5.18.2-thr"
  - "5.20.0"
  - "5.20.0-thr"
  - "5.20"
env:
  secure: "u60c2PCxcyKzjRfvHXcdbRwbfX8oOLz7Pmntwv+aAlZjlPCMUdwcO+dEEvIjDjyPQgIcCWKNCMO4oBl59g7yiOJ70Q+IL/BNB1hjuRp170BoJld60A6C5aXunalsA7c0DVkxJch3o+z98lw6nAIkXEvQTzSqz2U8AHB1UGsLPAg="
before_install:
  - sudo apt-get update -qq
  - git remote add builds git://github.com/travis-perl/builds
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - "[ \"${TRAVIS_PERL_VERSION/@*/}\" == \"system\" ] && export NO_COMMIT_PERL=1 || true"
  - "[ \"${TRAVIS_PERL_VERSION/@*/}\" == \"$PERLBREW_PERL\" ] && export NO_COMMIT_PERL=1 || true"
install:
  - ./per-local-lib $TRAVIS_PERL_VERSION ./build
script:
  - ./per-local-lib $TRAVIS_PERL_VERSION ./commit
after_success:
  - ./push $(./per-local-lib $TRAVIS_PERL_VERSION echo)
branches:
  exclude:
    - /^perl\//
    - /^libs\//
notifications:
  email: false
